import { Card } from './Card';

export const DECK: Card[] = [
    { id: 'A-D', rank: 'A', suit: 'D', color: 'R'},
    { id: 'A-H', rank: 'A', suit: 'H', color: 'R'},
    { id: 'A-S', rank: 'A', suit: 'S', color: 'B'},
    { id: 'A-C', rank: 'A', suit: 'C', color: 'B'},
    { id: '2-D', rank: '2', suit: 'D', color: 'R'},
    { id: '2-H', rank: '2', suit: 'H', color: 'R'},
    { id: '2-S', rank: '2', suit: 'S', color: 'B'},
    { id: '2-C', rank: '2', suit: 'C', color: 'B'},
    { id: '3-D', rank: '3', suit: 'D', color: 'R'},
    { id: '3-H', rank: '3', suit: 'H', color: 'R'},
    { id: '3-S', rank: '3', suit: 'S', color: 'B'},
    { id: '3-C', rank: '3', suit: 'C', color: 'B'},
    { id: '4-D', rank: '4', suit: 'D', color: 'R'},
    { id: '4-H', rank: '4', suit: 'H', color: 'R'},
    { id: '4-S', rank: '4', suit: 'S', color: 'B'},
    { id: '4-C', rank: '4', suit: 'C', color: 'B'},
    { id: '5-D', rank: '5', suit: 'D', color: 'R'},
    { id: '5-H', rank: '5', suit: 'H', color: 'R'},
    { id: '5-S', rank: '5', suit: 'S', color: 'B'},
    { id: '5-C', rank: '5', suit: 'C', color: 'B'},
    { id: '6-D', rank: '6', suit: 'D', color: 'R'},
    { id: '6-H', rank: '6', suit: 'H', color: 'R'},
    { id: '6-S', rank: '6', suit: 'S', color: 'B'},
    { id: '6-C', rank: '6', suit: 'C', color: 'B'},
    { id: '7-D', rank: '7', suit: 'D', color: 'R'},
    { id: '7-H', rank: '7', suit: 'H', color: 'R'},
    { id: '7-S', rank: '7', suit: 'S', color: 'B'},
    { id: '7-C', rank: '7', suit: 'C', color: 'B'},
    { id: '8-D', rank: '8', suit: 'D', color: 'R'},
    { id: '8-H', rank: '8', suit: 'H', color: 'R'},
    { id: '8-S', rank: '8', suit: 'S', color: 'B'},
    { id: '8-C', rank: '8', suit: 'C', color: 'B'},
    { id: '9-D', rank: '9', suit: 'D', color: 'R'},
    { id: '9-H', rank: '9', suit: 'H', color: 'R'},
    { id: '9-S', rank: '9', suit: 'S', color: 'B'},
    { id: '9-C', rank: '9', suit: 'C', color: 'B'},
    { id: '10-D', rank: '10', suit: 'D', color: 'R'},
    { id: '10-H', rank: '10', suit: 'H', color: 'R'},
    { id: '10-S', rank: '10', suit: 'S', color: 'B'},
    { id: '10-C', rank: '10', suit: 'C', color: 'B'},
    { id: 'J-D', rank: 'J', suit: 'D', color: 'R'},
    { id: 'J-H', rank: 'J', suit: 'H', color: 'R'},
    { id: 'J-S', rank: 'J', suit: 'S', color: 'B'},
    { id: 'J-C', rank: 'J', suit: 'C', color: 'B'},
    { id: 'Q-D', rank: 'Q', suit: 'D', color: 'R'},
    { id: 'Q-H', rank: 'Q', suit: 'H', color: 'R'},
    { id: 'Q-S', rank: 'Q', suit: 'S', color: 'B'},
    { id: 'Q-C', rank: 'Q', suit: 'C', color: 'B'},
    { id: 'K-D', rank: 'K', suit: 'D', color: 'R'},
    { id: 'K-H', rank: 'K', suit: 'H', color: 'R'},
    { id: 'K-S', rank: 'K', suit: 'S', color: 'B'},
    { id: 'K-C', rank: 'K', suit: 'C', color: 'B'}
];


